# Analysis options for OnFiNtY
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true

analyzer:
  errors:
    deprecated_member_use: ignore